authorized_users:
  - Ana Lucia Logistica
  - Oswaldo movilizador
  - Jose Luis movilizador
  - Freddy jefe de taller
  - Jhon gerente de operaciones
  - Walther gerente general
  - Angelica gerente comercial
  - Ivan gerente de compras
  - Cristian gerente de compras
  - Danna gerente de seguros
  - Ronald movilizador
